## 3 Main benefits of using numpy over python arrays

- less memory
- fast
- convenient

In [1]:
# imports
import numpy as np
import time
import sys

a = np.array([1, 2, 3])
print(a[0], a[1])

1 2


In [2]:
# 1. less memory

l = range(1000)
print(sys.getsizeof(5) * len(l))
array = np.arange(1000)
print(array.size * array.itemsize)

28000
8000


In [3]:
# 2. fast

SIZE = 10000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

start = time.time()
result = [x + y for x, y in zip(l1, l2)]
print(f"Python lists took {(time.time() - start) * 1000} ms")

start = time.time()
result = a1 + a2
print(f"Numpy took {(time.time() - start) * 1000} ms")

Python lists took 1.4269351959228516 ms
Numpy took 0.8966922760009766 ms


In [4]:
# 3. convenient

n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## Numpy Array operations

In [5]:
# Support for Multi-dimensional array

a = np.array([[1,2],[3,4], [5,6]])
a.ndim

2

In [6]:
a.itemsize

8

In [7]:
a.dtype

dtype('int64')

In [8]:
a = np.array([[1,2],[3,4], [5,6]], dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [9]:
a.size

6

In [10]:
a.shape

(3, 2)

In [11]:
# complex number
a = np.array([[1,2],[3,4], [5,6]], dtype = complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [12]:
# how to have a placeholder
# Syntax: np.zeros(shape)

np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [16]:
np.arange(1, 5, 2)

array([1, 3])

In [17]:
#linearly divide the space between 1 and 5 into 10 partitions
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
a = np.array([[1,2],[3,4], [5,6]], dtype = np.int64)
print(a)
a.reshape((2,3))

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# how to flatten the multi-dimensinal array
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [20]:
b = np.ones((2,3,4))
np.ravel(b)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [21]:
a.min()

1

In [22]:
a.max()

6

In [23]:
a.sum()

21

In [24]:
print(a)
a.sum(axis = 0)

[[1 2]
 [3 4]
 [5 6]]


array([ 9, 12])

In [25]:
print(a)
a.sum(axis = 1)

[[1 2]
 [3 4]
 [5 6]]


array([ 3,  7, 11])

In [26]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [27]:
# find standard deviation
np.std(a)

1.707825127659933

In [28]:
# Matrix product
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"a:\n{a}\nb:\n{b}")
print("Sum")
print(a+b)
print("Difference")
print(a-b)
print("Product")
print(a*b)
print("Divide")
print(a/b)
print("Matrics dot product")
print(a.dot(b))

a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
b:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Difference
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Product
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Divide
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrics dot product
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


### Indexing and slicing

In [29]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[0:4]

array([1, 2, 3, 4])

In [31]:
a[-1]

9

In [32]:
a[:3]

array([1, 2, 3])

In [33]:
a[5:-1]

array([6, 7, 8])

In [34]:
a[5:]

array([6, 7, 8, 9])

In [35]:
a = np.array([[6,7,8], [1,2,3], [9,3,2] ])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [36]:
a[1:2]

array([[1, 2, 3]])

In [37]:
a[0:2, 2]

array([8, 3])

In [38]:
a[-1]

array([9, 3, 2])

In [39]:
a[-1, 0:2]

array([9, 3])

In [40]:
a[:]

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [41]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [42]:
a[:,0:2]

array([[6, 7],
       [1, 2],
       [9, 3]])

In [43]:
# numpy arrays are iterable
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [44]:
a.flat

In [45]:
for i in a.flat:
    print(i)

6
7
8
1
2
3
9
3
2


### Horizontal and vertical stacking

In [46]:
a = np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
b = np.arange(6, 12).reshape((3,2))
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [48]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [53]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [57]:
b = np.hsplit(a, 3)
print(b)
np.array(b).shape

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


(3, 2, 5)

In [69]:
a = np.arange(30).reshape(15,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [70]:
b = np.vsplit(a,5)
b

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15],
        [16, 17]]),
 array([[18, 19],
        [20, 21],
        [22, 23]]),
 array([[24, 25],
        [26, 27],
        [28, 29]])]

### Indexing with boolean array

In [73]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [80]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [82]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

## Numpy nditer

In [83]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [128]:
a.flatten()

array([                  0,                   1,                   0,
       2118395047680534529,                   0,                   1,
                         0, 2118395047680534529,                   0,
                         1,                   0, 2118395047680534529])

In [96]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
for cell in a.ravel():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [127]:
a

array([[                  0,                   1,                   0,
        2118395047680534529],
       [                  0,                   1,                   0,
        2118395047680534529],
       [                  0,                   1,                   0,
        2118395047680534529]])

In [111]:
# C order
for i in np.nditer(a, order = 'C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [112]:
# F (Fortran) order
for i in np.nditer(a, order = 'F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [126]:
for i in np.nditer(a, order = 'F', flags = ["external_loop"]):
    print(i)

[0 0 0]
[1 1 1]
[0 0 0]
[2118395047680534529 2118395047680534529 2118395047680534529]


In [129]:
a = np.arange(12).reshape(3,4)
for i in np.nditer(a, op_flags = ["readwrite"]):
    i[...] = i**2
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [132]:
np.shape(a)

(3, 4)

In [139]:
b = np.arange(3,12,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [141]:
print(a,b)
for x,y in np.nditer([a,b]):
    print(x, y)

# Read general broadcasting rules from Numpy

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] [[ 3]
 [ 7]
 [11]]
0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
